'use client';

/*
 * Sellbase provider generated by `sellbase init`. Wrap your app with it once, e.g. in
 * app/layout.tsx: <SellbaseStoreProvider>{children}</SellbaseStoreProvider>
 */
import { SellbaseProvider } from '@sellbase/react';
import type { ReactNode } from 'react';

export function SellbaseStoreProvider({ children }: { children: ReactNode }) {
  return (
    <SellbaseProvider
      url={process.env.NEXT_PUBLIC_SELLBASE_URL ?? ''}
      anonKey={process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? ''}
    >
      {children}
    </SellbaseProvider>
  );
}
