const es = {
  nav: {
    home: 'Inicio',
    orders: 'Pedidos',
    agenda: 'Agenda',
    products: 'Productos',
    customers: 'Clientes',
    discounts: 'Descuentos',
    settings: 'Ajustes',
    signOut: 'Salir',
  },
  agenda: {
    title: 'Agenda',
    resources: 'Recursos y horarios',
    allResources: 'Todos',
    previous: '← Semana anterior',
    next: 'Semana siguiente →',
    today: 'Hoy',
    empty: 'No hay citas esta semana.',
    emptyPrompt:
      'Configura en Sellbase un servicio con su horario semanal para que mis clientes puedan agendar.',
    complete: 'Completar',
    noShow: 'No asistió',
    cancel: 'Cancelar',
    reschedule: 'Reagendar',
    pickTime: 'Elige el nuevo horario',
    noSlots: 'No hay horarios libres en los próximos 14 días.',
    reason: 'Motivo',
    refund: 'Reembolsar la cita',
    confirm: 'Confirmar',
    back: 'Volver',
    cancelImpact: 'La cita se cancelará y se avisará al cliente.',
    statuses: {
      confirmed: 'Confirmada',
      completed: 'Completada',
      no_show: 'No asistió',
      cancelled: 'Cancelada',
      rescheduled: 'Reagendada',
      held: 'Apartada',
      expired: 'Vencida',
    } as Record<string, string>,
  },
  resources: {
    title: 'Recursos y horarios',
    new: 'Nuevo recurso',
    name: 'Nombre',
    kind: 'Tipo',
    timezone: 'Zona horaria',
    hours: 'Horario semanal',
    closed: 'Cerrado',
    services: 'Servicios que atiende',
    noServices: 'Aún no hay productos de tipo servicio.',
    exceptions: 'Días bloqueados u horas extra',
    exceptionHint: 'Fechas y horas en la zona horaria de tu navegador.',
    from: 'Desde',
    to: 'Hasta',
    blocked: 'Bloqueado',
    extra: 'Horas extra',
    add: 'Agregar',
    remove: 'Quitar',
    save: 'Guardar',
    saved: 'Guardado',
    back: '← Agenda',
    kinds: { staff: 'Persona', room: 'Sala', equipment: 'Equipo' } as Record<string, string>,
    weekdays: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
  },
  login: {
    title: 'Entra a tu tienda',
    email: 'Correo',
    password: 'Contraseña',
    signIn: 'Entrar',
    magicLink: 'Enviarme un link de acceso',
    magicLinkSent: 'Revisa tu correo: te enviamos un link para entrar.',
    notStaff: 'Tu cuenta no es parte del equipo de esta tienda. Pide al dueño que te invite.',
  },
  home: {
    checks: {
      schema: 'Base de datos',
      rls: 'Seguridad (RLS)',
      store: 'Datos de la tienda',
      payments: 'Pagos',
      email: 'Correos de pedidos',
      catalog: 'Catálogo',
      webhooks: 'Webhooks de pago',
    } as Record<string, string>,
    title: 'Inicio',
    checklist: 'Lista de configuración',
    today: 'Ventas de hoy',
    last7: 'Últimos 7 días',
    last30: 'Últimos 30 días',
    ordersCount: (n: number) => (n === 1 ? '1 pedido' : `${n} pedidos`),
    average: 'ticket promedio',
    toFulfill: 'Pedidos por surtir',
    bookingsToday: 'Citas de hoy',
    salesChart: 'Ventas por día (30 días)',
    topProducts: 'Más vendidos (30 días)',
    noSales: 'Aún no hay ventas en estos 30 días.',
    units: (n: number) => (n === 1 ? '1 unidad' : `${n} unidades`),
    allGood: 'Todo listo para vender.',
    askAi: 'Pídeselo a tu IA',
    copy: 'Copiar',
    copied: 'Copiado',
  },
  orders: {
    title: 'Pedidos',
    empty: 'Aún no hay pedidos.',
    emptyPrompt:
      'Haz una compra de prueba en mi tienda con Sellbase y confírmame que llegó el pedido.',
    number: 'Pedido',
    customer: 'Cliente',
    total: 'Total',
    date: 'Fecha',
    status: 'Estado',
    all: 'Todos',
    items: 'Productos',
    payments: 'Pagos',
    timeline: 'Historial',
    shippingAddress: 'Dirección de envío',
    subtotal: 'Subtotal',
    discount: 'Descuento',
    shipping: 'Envío',
    back: '← Pedidos',
    actions: 'Acciones',
    fulfill: 'Marcar como enviado',
    carrier: 'Paquetería',
    trackingNumber: 'Número de guía',
    trackingUrl: 'URL de rastreo',
    notifyCustomer: 'Avisar al cliente por correo',
    refund: 'Reembolsar',
    refundAmount: 'Monto a reembolsar',
    reason: 'Motivo',
    cancelOrder: 'Cancelar pedido',
    restock: 'Regresar productos al inventario',
    refundToo: 'Reembolsar lo pagado',
    addNote: 'Agregar nota',
    balanceLink: 'Link de pago del saldo',
    balanceReady: 'Envía este link al cliente:',
    copy: 'Copiar',
    copied: 'Copiado',
    resend: 'Reenviar confirmación',
    resent: 'Confirmación enviada',
    confirm: 'Confirmar',
    back2: 'Volver',
    refundImpact: (amount: string, email: string) =>
      `Se reembolsarán ${amount} a ${email} vía Stripe. No se puede deshacer.`,
    cancelImpact: (refund: string | null) =>
      `El pedido quedará cancelado y los links de descarga dejarán de funcionar.${refund ? ` Se reembolsarán ${refund}.` : ''}`,
    shipments: 'Envíos',
    refunds: 'Reembolsos',
    track: 'Rastrear',
    refundable: (amount: string) => `Reembolsable: ${amount}`,
    events: {
      'order.created': 'Pedido pagado.',
      'digital.granted': (n: number) => `Links de descarga enviados (${n}).`,
      test_purchase: 'Compra de prueba: el stock se regresó al inventario.',
      'fulfillment.created': (qty: number, carrier: string | null, tracking: string | null) =>
        `Enviado: ${qty} producto(s)${carrier ? ` con ${carrier}` : ''}${tracking ? ` (guía ${tracking})` : ''}.`,
      'refund.created': (amount: string, reason: string) => `Reembolso de ${amount}: ${reason}.`,
      'order.cancelled': (reason: string) => `Pedido cancelado: ${reason}.`,
      'notification.requested': 'Se pidió reenviar el correo.',
      'inventory.oversold': (n: number) => `Faltó stock al confirmar el pago: ${n} unidad(es).`,
      emailSent: (template: string) => `Correo enviado: ${template}.`,
      templates: {
        order_confirmation: 'confirmación',
        order_shipped: 'pedido en camino',
        order_refunded: 'reembolso',
        order_cancelled: 'cancelación',
      } as Record<string, string>,
    },
  },
  products: {
    title: 'Productos',
    new: 'Nuevo producto',
    empty: 'Aún no tienes productos.',
    emptyPrompt: 'Crea en Sellbase un producto activo con foto, precio y stock para mi tienda.',
    search: 'Buscar por nombre o SKU',
    name: 'Nombre',
    type: 'Tipo',
    status: 'Estado',
    price: 'Precio',
    stock: 'Stock',
    description: 'Descripción',
    variants: 'Variantes',
    addVariant: 'Agregar variante',
    variantTitle: 'Variante',
    sku: 'SKU',
    save: 'Guardar',
    saved: 'Guardado',
    archive: 'Archivar',
    images: 'Imágenes',
    addImage: 'Agregar imagen',
    file: 'Archivo para el comprador',
    uploadFile: 'Subir archivo',
    requiresShipping: 'Requiere envío',
    weight: 'Peso (g)',
    back: '← Productos',
    types: { physical: 'Físico', digital: 'Digital', service: 'Servicio' },
    service: {
      duration: 'Duración (min)',
      bufferBefore: 'Margen antes (min)',
      bufferAfter: 'Margen después (min)',
      capacity: 'Cupo por horario',
      deposit: 'Anticipo (opcional)',
      location: 'Modalidad',
      inPerson: 'Presencial',
      online: 'En línea',
      meetingUrl: 'Link de la reunión',
      minNotice: 'Antelación mínima (min)',
      window: 'Se puede agendar hasta (días)',
      resources: 'Quién lo atiende',
      noResources: 'Crea primero un recurso en Agenda → Recursos y horarios.',
    },
    statuses: { draft: 'Borrador', active: 'Activo', archived: 'Archivado' },
  },
  settings: {
    title: 'Ajustes',
    store: 'Tienda',
    storeName: 'Nombre de la tienda',
    contactEmail: 'Correo de contacto',
    brandColor: 'Color de marca',
    taxRate: 'IVA (%)',
    taxIncluded: 'Los precios incluyen impuestos',
    shipping: 'Envío',
    flatRate: 'Tarifa fija',
    freeOver: 'Envío gratis desde',
    pickup: 'Permitir recoger en tienda',
    payments: 'Pagos',
    stripeConnected: 'Stripe conectado',
    stripeNotConnected: 'Stripe no está conectado',
    secretKey: 'Llave secreta (sk_…)',
    webhookSecret: 'Secreto del webhook (whsec_…)',
    connect: 'Conectar',
    test: 'Probar conexión',
    save: 'Guardar',
    saved: 'Guardado',
  },
  status: {
    pending_payment: 'Pago pendiente',
    open: 'Abierto',
    completed: 'Completado',
    cancelled: 'Cancelado',
    unpaid: 'Sin pagar',
    partially_paid: 'Anticipo',
    paid: 'Pagado',
    partially_refunded: 'Reembolso parcial',
    refunded: 'Reembolsado',
    unfulfilled: 'Por surtir',
    partially_fulfilled: 'Surtido parcial',
    fulfilled: 'Surtido',
  },
  customers: {
    title: 'Clientes',
    search: 'Buscar por correo, nombre o teléfono',
    empty: 'Aún no tienes clientes. Aparecen solos con cada compra.',
    emptyPrompt:
      'Haz una compra de prueba en mi tienda Sellbase para ver cómo llegan los clientes.',
    name: 'Cliente',
    orders: 'Pedidos',
    spent: 'Total gastado',
    lastOrder: 'Última compra',
    back: '← Clientes',
    since: 'Cliente desde',
    marketing: 'Acepta promociones',
    addresses: 'Direcciones',
    noAddresses: 'Sin direcciones guardadas.',
    history: 'Pedidos',
    noOrders: 'Sin pedidos.',
    bookings: 'Citas',
    noBookings: 'Sin citas.',
    loadMore: 'Ver más',
  },
  discounts: {
    title: 'Descuentos',
    new: 'Nuevo descuento',
    edit: 'Editar',
    empty: 'Aún no tienes descuentos.',
    emptyPrompt: 'Crea en mi tienda Sellbase un código BIENVENIDA de 10% para la primera compra.',
    code: 'Código',
    automatic: 'Automático (sin código)',
    kind: 'Tipo',
    kinds: {
      percent: 'Porcentaje',
      fixed: 'Monto fijo',
      free_shipping: 'Envío gratis',
    } as Record<string, string>,
    percent: 'Porcentaje (%)',
    amount: 'Monto',
    appliesTo: 'Aplica a',
    allProducts: 'Todos los productos',
    someCollections: 'Colecciones',
    someProducts: (n: number) => `${n} producto(s) (se configura desde la IA o la API)`,
    minSubtotal: 'Compra mínima',
    usageLimit: 'Usos totales',
    perCustomer: 'Usos por cliente',
    startsAt: 'Desde',
    endsAt: 'Hasta',
    optional: 'opcional',
    status: 'Estado',
    statuses: { active: 'Activo', disabled: 'Pausado' } as Record<string, string>,
    uses: (n: number, limit: number | null) => (limit ? `${n} de ${limit} usos` : `${n} usos`),
    save: 'Guardar descuento',
    saved: 'Descuento guardado.',
    remove: 'Eliminar',
    confirmRemove: 'Confirmar',
    removed: 'Descuento eliminado.',
    disabledInstead: 'Ya se usó en pedidos, así que se pausó en lugar de borrarlo.',
    close: 'Cerrar',
  },
  collections: {
    title: 'Colecciones',
    link: 'Colecciones',
    new: 'Nueva colección',
    back: '← Productos',
    empty: 'Aún no tienes colecciones.',
    emptyPrompt:
      'Crea en mi tienda Sellbase una colección "Lo más vendido" con mis 4 mejores productos.',
    name: 'Nombre',
    slug: 'URL',
    slugHint: (slug: string) => `Tu tienda la filtra con ?collection=${slug}`,
    description: 'Descripción',
    products: 'Productos (en este orden)',
    noProducts: 'Aún no tienes productos.',
    count: (n: number) => (n === 1 ? '1 producto' : `${n} productos`),
    save: 'Guardar',
    saved: 'Colección guardada.',
    remove: 'Eliminar colección',
    confirmRemove: 'Sí, eliminar (los productos se conservan)',
  },
  common: {
    loading: 'Cargando…',
    error: 'Algo salió mal.',
    retry: 'Reintentar',
    cancel: 'Cancelar',
    menu: 'Menú',
  },
};

export type Texts = typeof es;

const en: Texts = {
  nav: {
    home: 'Home',
    orders: 'Orders',
    agenda: 'Agenda',
    products: 'Products',
    customers: 'Customers',
    discounts: 'Discounts',
    settings: 'Settings',
    signOut: 'Sign out',
  },
  agenda: {
    title: 'Agenda',
    resources: 'Resources and hours',
    allResources: 'All',
    previous: '← Previous week',
    next: 'Next week →',
    today: 'Today',
    empty: 'No appointments this week.',
    emptyPrompt: 'Set up a Sellbase service with weekly hours so my customers can book.',
    complete: 'Complete',
    noShow: 'No-show',
    cancel: 'Cancel',
    reschedule: 'Reschedule',
    pickTime: 'Pick the new time',
    noSlots: 'No free times in the next 14 days.',
    reason: 'Reason',
    refund: 'Refund the appointment',
    confirm: 'Confirm',
    back: 'Back',
    cancelImpact: 'The appointment will be cancelled and the customer notified.',
    statuses: {
      confirmed: 'Confirmed',
      completed: 'Completed',
      no_show: 'No-show',
      cancelled: 'Cancelled',
      rescheduled: 'Rescheduled',
      held: 'Held',
      expired: 'Expired',
    } as Record<string, string>,
  },
  resources: {
    title: 'Resources and hours',
    new: 'New resource',
    name: 'Name',
    kind: 'Kind',
    timezone: 'Time zone',
    hours: 'Weekly hours',
    closed: 'Closed',
    services: 'Services delivered',
    noServices: 'No service products yet.',
    exceptions: 'Blocked days or extra hours',
    exceptionHint: 'Dates and times in your browser time zone.',
    from: 'From',
    to: 'To',
    blocked: 'Blocked',
    extra: 'Extra hours',
    add: 'Add',
    remove: 'Remove',
    save: 'Save',
    saved: 'Saved',
    back: '← Agenda',
    kinds: { staff: 'Person', room: 'Room', equipment: 'Equipment' } as Record<string, string>,
    weekdays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  },
  login: {
    title: 'Sign in to your store',
    email: 'Email',
    password: 'Password',
    signIn: 'Sign in',
    magicLink: 'Email me a sign-in link',
    magicLinkSent: 'Check your inbox for a sign-in link.',
    notStaff: 'Your account is not on this store’s team. Ask the owner to invite you.',
  },
  home: {
    checks: {
      schema: 'Database',
      rls: 'Security (RLS)',
      store: 'Store details',
      payments: 'Payments',
      email: 'Order emails',
      catalog: 'Catalog',
      webhooks: 'Payment webhooks',
    } as Record<string, string>,
    title: 'Home',
    checklist: 'Setup checklist',
    today: 'Sales today',
    last7: 'Last 7 days',
    last30: 'Last 30 days',
    ordersCount: (n: number) => (n === 1 ? '1 order' : `${n} orders`),
    average: 'average order',
    toFulfill: 'Orders to fulfill',
    bookingsToday: 'Appointments today',
    salesChart: 'Sales per day (30 days)',
    topProducts: 'Best sellers (30 days)',
    noSales: 'No sales in the last 30 days yet.',
    units: (n: number) => (n === 1 ? '1 unit' : `${n} units`),
    allGood: 'Ready to sell.',
    askAi: 'Ask your AI',
    copy: 'Copy',
    copied: 'Copied',
  },
  orders: {
    title: 'Orders',
    empty: 'No orders yet.',
    emptyPrompt: 'Make a test purchase in my Sellbase store and confirm the order arrived.',
    number: 'Order',
    customer: 'Customer',
    total: 'Total',
    date: 'Date',
    status: 'Status',
    all: 'All',
    items: 'Items',
    payments: 'Payments',
    timeline: 'Timeline',
    shippingAddress: 'Shipping address',
    subtotal: 'Subtotal',
    discount: 'Discount',
    shipping: 'Shipping',
    back: '← Orders',
    actions: 'Actions',
    fulfill: 'Mark as shipped',
    carrier: 'Carrier',
    trackingNumber: 'Tracking number',
    trackingUrl: 'Tracking URL',
    notifyCustomer: 'Email the customer',
    refund: 'Refund',
    refundAmount: 'Amount to refund',
    reason: 'Reason',
    cancelOrder: 'Cancel order',
    restock: 'Return items to stock',
    refundToo: 'Refund what was paid',
    addNote: 'Add note',
    balanceLink: 'Balance payment link',
    balanceReady: 'Send this link to the customer:',
    copy: 'Copy',
    copied: 'Copied',
    resend: 'Resend confirmation',
    resent: 'Confirmation sent',
    confirm: 'Confirm',
    back2: 'Back',
    refundImpact: (amount: string, email: string) =>
      `${amount} will be refunded to ${email} through Stripe. This cannot be undone.`,
    cancelImpact: (refund: string | null) =>
      `The order will be cancelled and download links will stop working.${refund ? ` ${refund} will be refunded.` : ''}`,
    shipments: 'Shipments',
    refunds: 'Refunds',
    track: 'Track',
    refundable: (amount: string) => `Refundable: ${amount}`,
    events: {
      'order.created': 'Order paid.',
      'digital.granted': (n: number) => `Download links sent (${n}).`,
      test_purchase: 'Test purchase: stock was returned.',
      'fulfillment.created': (qty: number, carrier: string | null, tracking: string | null) =>
        `Shipped ${qty} item(s)${carrier ? ` with ${carrier}` : ''}${tracking ? ` (tracking ${tracking})` : ''}.`,
      'refund.created': (amount: string, reason: string) => `Refunded ${amount}: ${reason}.`,
      'order.cancelled': (reason: string) => `Order cancelled: ${reason}.`,
      'notification.requested': 'Email resend requested.',
      'inventory.oversold': (n: number) => `Stock ran out before payment: ${n} unit(s).`,
      emailSent: (template: string) => `Email sent: ${template}.`,
      templates: {
        order_confirmation: 'confirmation',
        order_shipped: 'order shipped',
        order_refunded: 'refund',
        order_cancelled: 'cancellation',
      } as Record<string, string>,
    },
  },
  products: {
    title: 'Products',
    new: 'New product',
    empty: 'No products yet.',
    emptyPrompt: 'Create an active Sellbase product with a photo, price and stock for my store.',
    search: 'Search by name or SKU',
    name: 'Name',
    type: 'Type',
    status: 'Status',
    price: 'Price',
    stock: 'Stock',
    description: 'Description',
    variants: 'Variants',
    addVariant: 'Add variant',
    variantTitle: 'Variant',
    sku: 'SKU',
    save: 'Save',
    saved: 'Saved',
    archive: 'Archive',
    images: 'Images',
    addImage: 'Add image',
    file: 'File for the buyer',
    uploadFile: 'Upload file',
    requiresShipping: 'Requires shipping',
    weight: 'Weight (g)',
    back: '← Products',
    types: { physical: 'Physical', digital: 'Digital', service: 'Service' },
    service: {
      duration: 'Duration (min)',
      bufferBefore: 'Buffer before (min)',
      bufferAfter: 'Buffer after (min)',
      capacity: 'Seats per time',
      deposit: 'Deposit (optional)',
      location: 'Location',
      inPerson: 'In person',
      online: 'Online',
      meetingUrl: 'Meeting link',
      minNotice: 'Minimum notice (min)',
      window: 'Bookable up to (days ahead)',
      resources: 'Who delivers it',
      noResources: 'Create a resource first in Agenda → Resources and hours.',
    },
    statuses: { draft: 'Draft', active: 'Active', archived: 'Archived' },
  },
  settings: {
    title: 'Settings',
    store: 'Store',
    storeName: 'Store name',
    contactEmail: 'Contact email',
    brandColor: 'Brand color',
    taxRate: 'Tax (%)',
    taxIncluded: 'Prices include tax',
    shipping: 'Shipping',
    flatRate: 'Flat rate',
    freeOver: 'Free shipping over',
    pickup: 'Allow in-store pickup',
    payments: 'Payments',
    stripeConnected: 'Stripe connected',
    stripeNotConnected: 'Stripe is not connected',
    secretKey: 'Secret key (sk_…)',
    webhookSecret: 'Webhook secret (whsec_…)',
    connect: 'Connect',
    test: 'Test connection',
    save: 'Save',
    saved: 'Saved',
  },
  status: {
    pending_payment: 'Payment pending',
    open: 'Open',
    completed: 'Completed',
    cancelled: 'Cancelled',
    unpaid: 'Unpaid',
    partially_paid: 'Deposit',
    paid: 'Paid',
    partially_refunded: 'Partially refunded',
    refunded: 'Refunded',
    unfulfilled: 'To fulfill',
    partially_fulfilled: 'Partially fulfilled',
    fulfilled: 'Fulfilled',
  },
  customers: {
    title: 'Customers',
    search: 'Search by email, name or phone',
    empty: 'No customers yet. They appear with every purchase.',
    emptyPrompt: 'Run a test purchase in my Sellbase store to see customers come in.',
    name: 'Customer',
    orders: 'Orders',
    spent: 'Total spent',
    lastOrder: 'Last order',
    back: '← Customers',
    since: 'Customer since',
    marketing: 'Accepts marketing',
    addresses: 'Addresses',
    noAddresses: 'No saved addresses.',
    history: 'Orders',
    noOrders: 'No orders.',
    bookings: 'Appointments',
    noBookings: 'No appointments.',
    loadMore: 'Load more',
  },
  discounts: {
    title: 'Discounts',
    new: 'New discount',
    edit: 'Edit',
    empty: 'No discounts yet.',
    emptyPrompt: 'Create a WELCOME code in my Sellbase store: 10% off the first purchase.',
    code: 'Code',
    automatic: 'Automatic (no code)',
    kind: 'Type',
    kinds: {
      percent: 'Percentage',
      fixed: 'Fixed amount',
      free_shipping: 'Free shipping',
    } as Record<string, string>,
    percent: 'Percentage (%)',
    amount: 'Amount',
    appliesTo: 'Applies to',
    allProducts: 'All products',
    someCollections: 'Collections',
    someProducts: (n: number) => `${n} product(s) (set up from your AI or the API)`,
    minSubtotal: 'Minimum purchase',
    usageLimit: 'Total uses',
    perCustomer: 'Uses per customer',
    startsAt: 'From',
    endsAt: 'Until',
    optional: 'optional',
    status: 'Status',
    statuses: { active: 'Active', disabled: 'Paused' } as Record<string, string>,
    uses: (n: number, limit: number | null) => (limit ? `${n} of ${limit} uses` : `${n} uses`),
    save: 'Save discount',
    saved: 'Discount saved.',
    remove: 'Delete',
    confirmRemove: 'Confirm',
    removed: 'Discount deleted.',
    disabledInstead: 'It was used in orders, so it was paused instead of deleted.',
    close: 'Close',
  },
  collections: {
    title: 'Collections',
    link: 'Collections',
    new: 'New collection',
    back: '← Products',
    empty: 'No collections yet.',
    emptyPrompt: 'Create a "Best sellers" collection in my Sellbase store with my top 4 products.',
    name: 'Name',
    slug: 'URL',
    slugHint: (slug: string) => `Your store filters it with ?collection=${slug}`,
    description: 'Description',
    products: 'Products (in this order)',
    noProducts: 'No products yet.',
    count: (n: number) => (n === 1 ? '1 product' : `${n} products`),
    save: 'Save',
    saved: 'Collection saved.',
    remove: 'Delete collection',
    confirmRemove: 'Yes, delete (products are kept)',
  },
  common: {
    loading: 'Loading…',
    error: 'Something went wrong.',
    retry: 'Retry',
    cancel: 'Cancel',
    menu: 'Menu',
  },
};

export const texts = { es, en };
