/*
 * Admin v2 copy (shell, setup guide, product editor, inventory, abandoned carts, order
 * view, settings sections). Merged into `texts` so stores override it the same way.
 */

export const esV2 = {
  shell: {
    search: 'Buscar',
    searchLabel: 'Buscar productos, pedidos y clientes',
    searching: 'Buscando…',
    noResults: 'Sin resultados',
    groups: { products: 'Productos', orders: 'Pedidos', customers: 'Clientes' },
    viewStore: 'Ver tienda',
    salesChannels: 'Canales de venta',
    onlineStore: 'Tienda en línea',
    account: 'Cuenta',
    unsaved: 'Cambios sin guardar',
    discard: 'Descartar',
    save: 'Guardar',
    poweredBy: 'Hecho con Sellbase',
  },
  nav2: {
    abandoned: 'Carritos abandonados',
    inventory: 'Inventario',
    collections: 'Colecciones',
    newOrder: 'Nuevo pedido',
  },
  setup: {
    greeting: (name: string) => (name ? `Hola, ${name}` : 'Hola'),
    title: 'Guía de configuración',
    intro: 'Sigue estos pasos para dejar tu tienda lista para vender.',
    progress: (done: number, total: number) => `${done} de ${total} tareas completadas`,
    hide: 'Ocultar guía',
    show: 'Mostrar guía de configuración',
    allDone: '¡Tu tienda está lista para vender!',
    steps: {
      catalog: {
        title: 'Agrega tu primer producto',
        body: 'Escribe un título, sube fotos, pon el precio y cuántas piezas tienes.',
        action: 'Agregar producto',
      },
      brand: {
        title: 'Personaliza tu marca',
        body: 'Sube tu logo, elige tu color y el correo donde tus clientes te escriben.',
        action: 'Personalizar',
      },
      payments: {
        title: 'Activa los pagos',
        body: 'Conecta Stripe para cobrar con tarjeta. Empieza en modo prueba; cambias a real cuando quieras.',
        action: 'Configurar pagos',
      },
      shipping: {
        title: 'Revisa tus envíos',
        body: 'Define cuánto cobras por envío y desde qué monto es gratis.',
        action: 'Configurar envíos',
      },
      email: {
        title: 'Conecta los correos',
        body: 'Tus clientes reciben confirmaciones, envíos y descargas desde tu dominio con Resend.',
        action: 'Conectar correos',
      },
      webhooks: {
        title: 'Haz una compra de prueba',
        body: 'Comprueba que los pagos llegan y los pedidos se crean solos.',
        action: 'Revisar pagos',
      },
      store: {
        title: 'Completa los datos de la tienda',
        body: 'Falta el correo de contacto de la tienda.',
        action: 'Completar',
      },
      site: {
        title: 'Conecta tu sitio',
        body: 'Pon la dirección de tu tienda para que los correos de carritos abandonados lleven a ella.',
        action: 'Agregar URL',
      },
      schema: {
        title: 'Actualiza Sellbase',
        body: 'Hay migraciones pendientes. Pídele a tu IA que corra `sellbase upgrade`.',
        action: 'Copiar instrucción',
      },
      other: { action: 'Ver detalle' },
    } as Record<string, { title?: string; body?: string; action: string }>,
    pending: 'Pendiente',
    done: 'Listo',
    todo: 'Pendientes de hoy',
    toFulfill: (n: number) => (n === 1 ? '1 pedido por preparar' : `${n} pedidos por preparar`),
    unpaid: (n: number) => (n === 1 ? '1 pedido esperando pago' : `${n} pedidos esperando pago`),
    abandoned: (n: number) =>
      n === 1 ? '1 carrito abandonado por recuperar' : `${n} carritos abandonados por recuperar`,
    lowStock: (n: number) =>
      n === 1 ? '1 producto con poco inventario' : `${n} productos con poco inventario`,
    allClear: 'No hay pendientes. ¡Buen trabajo!',
  },
  list: {
    tabs: { all: 'Todos', active: 'Activos', draft: 'Borradores', archived: 'Archivados' },
    inventory: (units: number, variants: number) =>
      variants > 1 ? `${units} en inventario para ${variants} variantes` : `${units} en inventario`,
    untracked: 'Sin control de inventario',
    outOfStock: 'Agotado',
    variants: (n: number) => (n === 1 ? '1 variante' : `${n} variantes`),
    noResults: 'Ningún producto coincide con la búsqueda.',
    export: 'Exportar',
    more: 'Más acciones',
    emptyBody:
      'Agrega tus productos con fotos, precio e inventario, o impórtalos desde un CSV (Shopify incluido).',
    importCsv: 'Importar',
    allTypes: 'Todos los tipos',
  },
  editor: {
    add: 'Agregar producto',
    titleLabel: 'Título',
    titlePlaceholder: 'Ej. Mezcal Espadín 750 ml',
    description: 'Descripción',
    descriptionPlaceholder: 'Cuenta qué es, para quién es y por qué vale la pena.',
    media: 'Multimedia',
    drop: 'Arrastra imágenes aquí',
    or: 'o',
    upload: 'Subir imágenes',
    addUrl: 'Agregar desde URL',
    urlPlaceholder: 'https://…/foto.jpg',
    addUrlButton: 'Agregar',
    formats: 'JPG, PNG, WebP o GIF · máx. 5 MB',
    main: 'Principal',
    pending: 'Se sube al guardar',
    uploading: 'Subiendo…',
    alt: 'Texto alternativo',
    altHint: 'Describe la foto para lectores de pantalla y buscadores.',
    removeImage: 'Quitar imagen',
    moveLeft: 'Mover antes',
    moveRight: 'Mover después',
    makeMain: 'Hacer principal',
    tooBig: (name: string) => `${name} pesa más de 5 MB.`,
    notImage: (name: string) => `${name} no es una imagen.`,
    pricing: 'Precio',
    price: 'Precio',
    compareAt: 'Precio de comparación',
    compareAtHint: 'Precio anterior, se muestra tachado. Déjalo vacío si no hay oferta.',
    inventory: 'Inventario',
    track: 'Controlar inventario',
    trackHint: 'Descuenta piezas con cada venta y evita vender lo que no tienes.',
    quantity: 'Cantidad',
    sku: 'SKU (código de producto)',
    continueSelling: 'Seguir vendiendo aunque se agote',
    shipping: 'Envío',
    physical: 'Es un producto físico que se envía',
    weight: 'Peso',
    variants: 'Variantes',
    addOptions: 'Agregar opciones como talla o color',
    optionName: 'Nombre de la opción',
    optionNamePlaceholder: 'Talla, Color, Presentación…',
    optionValues: 'Valores',
    valuePlaceholder: 'Agrega un valor y presiona Enter',
    addValue: 'Agregar valor',
    addOption: 'Agregar otra opción',
    removeOption: 'Quitar opción',
    optionsDone: 'Listo',
    editOptions: 'Editar opciones',
    variant: 'Variante',
    available: 'Disponible',
    maxOptions: 'Hasta 3 opciones.',
    status: 'Estado',
    statusHint: {
      active: 'Visible en tu tienda.',
      draft: 'Oculto hasta que lo publiques.',
      archived: 'Oculto y fuera del catálogo.',
    } as Record<string, string>,
    organization: 'Organización del producto',
    type: 'Tipo',
    typeLocked: 'El tipo no cambia después de crear el producto.',
    typeHints: {
      physical: 'Se envía o se recoge.',
      digital: 'El cliente descarga un archivo.',
      service: 'El cliente agenda una cita.',
    } as Record<string, string>,
    collections: 'Colecciones',
    noCollections: 'Aún no tienes colecciones.',
    manageCollections: 'Administrar colecciones',
    tags: 'Etiquetas',
    tagsPlaceholder: 'Escribe y presiona Enter',
    removeTag: (tag: string) => `Quitar ${tag}`,
    seo: 'Anuncio en motores de búsqueda',
    seoHint: 'Así se verá tu producto en Google.',
    seoEdit: 'Editar',
    seoTitle: 'Título de la página',
    seoDescription: 'Metadescripción',
    chars: (n: number, max: number) => `${n} de ${max} caracteres`,
    urlPreview: (slug: string) => `…/products/${slug || 'tu-producto'}`,
    digital: 'Archivo digital',
    digitalHint: 'Tus clientes reciben un link de descarga seguro al pagar.',
    digitalSaveFirst: 'Guarda el producto para subir el archivo.',
    service: 'Detalles del servicio',
    saved: 'Producto guardado',
    created: 'Producto creado',
    archived: 'Producto archivado',
    archiveConfirm:
      'El producto dejará de verse en tu tienda. Los pedidos anteriores se conservan.',
    archiveTitle: (title: string) => `¿Archivar ${title}?`,
    duplicate: 'Duplicar',
    viewInStore: 'Ver en la tienda',
    back: 'Productos',
    unsavedLeave: 'Tienes cambios sin guardar.',
    required: 'Escribe un título.',
    priceRequired: 'Pon un precio.',
  },
  inventoryPage: {
    title: 'Inventario',
    intro: 'Cuántas piezas tienes de cada variante. Lo apartado es lo que está en pago.',
    search: 'Buscar por producto o SKU',
    tabs: { all: 'Todo', low: 'Poco inventario', out: 'Agotado' },
    product: 'Producto',
    sku: 'SKU',
    reserved: 'Apartado',
    available: 'Disponible',
    onHand: 'En existencia',
    adjust: 'Ajustar',
    setTo: 'Nuevo total',
    save: 'Guardar',
    untracked: 'No se controla',
    track: 'Controlar',
    reason: 'Ajuste manual en Inventario',
    updated: 'Inventario actualizado',
    empty: 'Nada por aquí.',
    emptyBody: 'Cuando tus productos tengan inventario, aparecerán aquí.',
    threshold: (n: number) => `Mostrando variantes con ${n} piezas o menos.`,
    add: (n: number) => `+${n}`,
    remove: (n: number) => `−${n}`,
  },
  abandoned: {
    title: 'Carritos abandonados',
    intro:
      'Clientes que llegaron a pagar y no terminaron. Mándales un correo con su carrito listo para comprar.',
    tabs: { all: 'Todos', abandoned: 'Sin recuperar', recovered: 'Recuperados' },
    checkout: 'Checkout',
    date: 'Fecha',
    customer: 'Cliente',
    items: 'Productos',
    total: 'Total',
    recovery: 'Recuperación',
    statuses: {
      abandoned: 'No recuperado',
      in_progress: 'Pagando',
      recovered: 'Recuperado',
    } as Record<string, string>,
    sentAt: (when: string) => `Correo enviado · ${when}`,
    notSent: 'Correo no enviado',
    send: 'Enviar correo',
    resend: 'Reenviar',
    copyLink: 'Copiar link del carrito',
    copied: 'Link copiado',
    sent: (email: string) => `Correo enviado a ${email}`,
    order: (n: number) => `Pedido #${n}`,
    more: (n: number) => `y ${n} más`,
    empty: 'Sin carritos abandonados',
    emptyBody:
      'Cuando alguien escriba su correo en el checkout y no pague, lo verás aquí para recuperarlo.',
    autoOn: 'Los correos de recuperación se envían solos.',
    autoOff: 'Activa el envío automático para no perder ventas.',
    configure: 'Configurar',
    noSite: 'Para enviar correos de recuperación, agrega la URL de tu tienda.',
    addSite: 'Agregar URL',
    loadMore: 'Ver más',
  },
  orderView: {
    tabs: {
      all: 'Todos',
      unfulfilled: 'Por preparar',
      unpaid: 'Sin pagar',
      open: 'Abiertos',
      closed: 'Cerrados',
    },
    unfulfilled: 'Por preparar',
    fulfilled: 'Preparado',
    digital: 'Entrega digital',
    booking: 'Cita',
    paid: 'Pagado',
    pending: 'Pago pendiente',
    subtotalItems: (n: number) => (n === 1 ? '1 artículo' : `${n} artículos`),
    taxes: 'Impuestos',
    total: 'Total',
    paidByCustomer: 'Pagado por el cliente',
    refunded: 'Reembolsado',
    balance: 'Saldo pendiente',
    net: 'Neto',
    printSlip: 'Imprimir hoja de empaque',
    more: 'Más acciones',
    notes: 'Notas',
    noNotes: 'Sin notas del cliente.',
    contact: 'Información de contacto',
    viewCustomer: 'Ver cliente',
    consents: 'Confirmaciones',
    comment: 'Deja un comentario…',
    post: 'Publicar',
    commentPosted: 'Comentario agregado',
    timeline: 'Historial',
    noShippingAddress: 'Sin dirección de envío',
    channel: 'Canal',
    placed: (when: string) => `Realizado el ${when}`,
    shippedWith: (carrier: string) => `Enviado con ${carrier}`,
    fulfilledToast: 'Pedido marcado como enviado',
    refundedToast: 'Reembolso hecho',
    cancelledToast: 'Pedido cancelado',
    resentToast: 'Confirmación reenviada',
    slip: {
      title: 'Hoja de empaque',
      order: (n: number) => `Pedido #${n}`,
      shipTo: 'Enviar a',
      billTo: 'Cliente',
      items: 'Artículos',
      qty: 'Cantidad',
      thanks: '¡Gracias por tu compra!',
      print: 'Imprimir',
    },
    noOrders: 'Ningún pedido coincide con los filtros.',
    paymentCol: 'Estado del pago',
    fulfillmentCol: 'Estado de preparación',
    moreFilters: 'Más filtros',
  },
  settingsNav: {
    title: 'Ajustes',
    sections: {
      general: 'General',
      payments: 'Pagos',
      shipping: 'Envíos y entregas',
      taxes: 'Impuestos',
      checkout: 'Checkout',
      notifications: 'Notificaciones',
      team: 'Equipo',
      agents: 'Agentes IA',
      webhooks: 'Webhooks',
      integrations: 'Integraciones',
    } as Record<string, string>,
    descriptions: {
      general: 'Nombre, logo, color y contacto de la tienda',
      payments: 'Stripe, modo prueba y cobros reales',
      shipping: 'Tarifas, envío gratis y recoger en tienda',
      taxes: 'IVA y cómo se muestran los precios',
      checkout: 'URL de la tienda, confirmaciones y carritos abandonados',
      notifications: 'Correos a tus clientes',
      team: 'Quién entra al admin',
      agents: 'Tokens y bitácora de tu IA',
      webhooks: 'Envía eventos a otros sistemas',
      integrations: 'Conexiones y APIs',
    } as Record<string, string>,
  },
  general: {
    details: 'Datos de la tienda',
    name: 'Nombre de la tienda',
    contact: 'Correo de contacto',
    contactHint: 'Aparece en los correos a tus clientes para que te puedan escribir.',
    brand: 'Marca',
    logo: 'Logo',
    logoHint: 'PNG, JPG, WebP o SVG, máx. 2 MB. Se usa en el admin y en los correos.',
    uploadLogo: 'Subir logo',
    changeLogo: 'Cambiar',
    removeLogo: 'Quitar',
    color: 'Color de marca',
    colorHint: 'Botones de los correos a tus clientes.',
    regional: 'Región',
    currency: 'Moneda',
    country: 'País',
    timezone: 'Zona horaria',
    regionalHint: 'La moneda se define al instalar; tus precios y pedidos se guardan en ella.',
    saved: 'Ajustes guardados',
    logoSaved: 'Logo actualizado',
  },
  shippingSettings: {
    rates: 'Tarifas de envío',
    ratesHint: 'Lo que ve tu cliente al pagar.',
    flat: 'Envío estándar',
    freeOver: 'Envío gratis a partir de',
    freeOverHint: 'Déjalo vacío si no ofreces envío gratis.',
    pickup: 'Recoger en tienda',
    pickupHint: 'Tus clientes pueden elegir recoger sin costo.',
    preview: 'Vista previa en el checkout',
    free: 'Gratis',
    previewFree: (amount: string) => `Gratis en compras desde ${amount}`,
  },
  taxSettings: {
    title: 'Impuestos',
    rate: 'Tasa de impuesto',
    included: 'Mis precios ya incluyen impuestos',
    includedHint: 'Recomendado en México: el precio que ves es el que paga el cliente.',
    shipping: 'Cobrar impuestos sobre el envío',
    example: (price: string, tax: string) =>
      `Ejemplo: en un producto de ${price}, el impuesto es ${tax}.`,
  },
  checkoutSettings: {
    site: 'Tu tienda en línea',
    siteUrl: 'URL de la tienda',
    siteUrlHint:
      'Donde está tu tienda. Se usa en los correos de carritos abandonados y como regreso de los links de pago.',
    consent: 'Casilla obligatoria',
    consentToggle: 'Pedir una confirmación antes de pagar',
    consentHint:
      'Útil para alcohol, edad mínima o términos. Se guarda con cada pedido como prueba.',
    consentText: 'Texto de la casilla',
    consentPlaceholder: 'Confirmo que soy mayor de 18 años',
    downloads: 'Página de descargas',
    downloadsUrl: 'URL de la página de descargas (opcional)',
    downloadsHint:
      'Para productos digitales. Debe contener {token}, p. ej. https://tutienda.com/descargas/{token}.',
    abandoned: 'Carritos abandonados',
    autoEmail: 'Enviar correo de recuperación automáticamente',
    autoEmailHint: 'Una sola vez por carrito, con un link que abre su carrito listo para pagar.',
    delay: 'Enviar después de',
    hours: (n: number) => (n === 1 ? '1 hora' : `${n} horas`),
    needsSite: 'Agrega la URL de tu tienda para activar los correos de recuperación.',
  },
  notificationSettings: {
    provider: 'Proveedor de correo',
    connected: 'Resend conectado',
    notConnected: 'Sin conectar',
    notConnectedHint:
      'Mientras no conectes Resend, los correos solo quedan en el registro del servidor y tus clientes no los reciben.',
    apiKey: 'API key de Resend (re_…)',
    apiKeyHint: 'Créala en resend.com/api-keys. Se guarda cifrada en Supabase Vault.',
    connect: 'Conectar Resend',
    reconnect: 'Cambiar API key',
    test: 'Enviar correo de prueba',
    testTo: 'Enviar a',
    testSent: 'Correo de prueba enviado',
    testLogged:
      'Resend no está conectado: el correo de prueba solo quedó en el registro del servidor.',
    sender: 'Remitente',
    senderHint: (from: string) =>
      `Se envía como “${from}”. Cámbialo con la variable SELLBASE_EMAIL_FROM.`,
    automatic: 'Correos automáticos',
    automaticHint: 'Se envían solos con tu logo y color.',
    templates: {
      order_confirmation: 'Confirmación de pedido (con descargas y citas)',
      order_shipped: 'Pedido en camino (con rastreo)',
      order_refunded: 'Reembolso',
      order_cancelled: 'Pedido cancelado',
      booking_reminder: 'Recordatorio de cita (24 h y 2 h antes)',
      booking_changed: 'Cita reagendada o cancelada',
      cart_recovery: 'Carrito abandonado (si lo activas en Checkout)',
    } as Record<string, string>,
  },
  integrationsPage: {
    intro:
      'Conecta servicios con tus llaves de API. Se guardan cifradas en Supabase Vault, nunca en tu código.',
    connected: 'Conectado',
    notConnected: 'Sin conectar',
    error: 'Con error',
    manage: 'Administrar',
    connect: 'Conectar',
    stripe: { name: 'Stripe', body: 'Pagos con tarjeta, OXXO y más.' },
    resend: { name: 'Resend', body: 'Correos transaccionales con tu dominio.' },
    agents: {
      name: 'Tu IA (MCP)',
      body: 'Claude, Cursor u otro agente opera la tienda con permisos limitados.',
    },
    webhooks: { name: 'Webhooks', body: 'Envía pedidos y eventos a tu ERP, hojas o Zapier.' },
    api: {
      name: 'API y SDK',
      body: 'Tu sitio usa la API pública de la tienda (catálogo, carrito, checkout).',
    },
    apiUrl: 'URL de la API',
    docs: 'Documentación',
    active: (n: number) => (n === 1 ? '1 activo' : `${n} activos`),
  },
};

export type TextsV2 = typeof esV2;

export const enV2: TextsV2 = {
  shell: {
    search: 'Search',
    searchLabel: 'Search products, orders and customers',
    searching: 'Searching…',
    noResults: 'No results',
    groups: { products: 'Products', orders: 'Orders', customers: 'Customers' },
    viewStore: 'View store',
    salesChannels: 'Sales channels',
    onlineStore: 'Online store',
    account: 'Account',
    unsaved: 'Unsaved changes',
    discard: 'Discard',
    save: 'Save',
    poweredBy: 'Made with Sellbase',
  },
  nav2: {
    abandoned: 'Abandoned checkouts',
    inventory: 'Inventory',
    collections: 'Collections',
    newOrder: 'New order',
  },
  setup: {
    greeting: (name: string) => (name ? `Hi, ${name}` : 'Hi'),
    title: 'Setup guide',
    intro: 'Follow these steps to get your store ready to sell.',
    progress: (done: number, total: number) => `${done} of ${total} tasks complete`,
    hide: 'Hide guide',
    show: 'Show setup guide',
    allDone: 'Your store is ready to sell!',
    steps: {
      catalog: {
        title: 'Add your first product',
        body: 'Write a title, upload photos, set the price and how many you have.',
        action: 'Add product',
      },
      brand: {
        title: 'Customize your brand',
        body: 'Upload your logo, pick your color and the email customers can write to.',
        action: 'Customize',
      },
      payments: {
        title: 'Set up payments',
        body: 'Connect Stripe to take cards. Start in test mode; go live when you are ready.',
        action: 'Set up payments',
      },
      shipping: {
        title: 'Review shipping',
        body: 'Set what you charge for shipping and when it is free.',
        action: 'Set up shipping',
      },
      email: {
        title: 'Connect email',
        body: 'Customers get confirmations, shipping updates and downloads from your domain with Resend.',
        action: 'Connect email',
      },
      webhooks: {
        title: 'Make a test purchase',
        body: 'Check that payments arrive and orders are created automatically.',
        action: 'Review payments',
      },
      store: {
        title: 'Complete your store details',
        body: 'The store contact email is missing.',
        action: 'Complete',
      },
      site: {
        title: 'Connect your site',
        body: 'Add your store address so abandoned checkout emails link back to it.',
        action: 'Add URL',
      },
      schema: {
        title: 'Update Sellbase',
        body: 'There are pending migrations. Ask your AI to run `sellbase upgrade`.',
        action: 'Copy instruction',
      },
      other: { action: 'See details' },
    },
    pending: 'Pending',
    done: 'Done',
    todo: 'Things to do today',
    toFulfill: (n: number) => (n === 1 ? '1 order to fulfill' : `${n} orders to fulfill`),
    unpaid: (n: number) => (n === 1 ? '1 order awaiting payment' : `${n} orders awaiting payment`),
    abandoned: (n: number) =>
      n === 1 ? '1 abandoned checkout to recover' : `${n} abandoned checkouts to recover`,
    lowStock: (n: number) => (n === 1 ? '1 product low on stock' : `${n} products low on stock`),
    allClear: 'Nothing pending. Nice work!',
  },
  list: {
    tabs: { all: 'All', active: 'Active', draft: 'Draft', archived: 'Archived' },
    inventory: (units: number, variants: number) =>
      variants > 1 ? `${units} in stock for ${variants} variants` : `${units} in stock`,
    untracked: 'Inventory not tracked',
    outOfStock: 'Out of stock',
    variants: (n: number) => (n === 1 ? '1 variant' : `${n} variants`),
    noResults: 'No products match your search.',
    export: 'Export',
    more: 'More actions',
    emptyBody: 'Add your products with photos, price and inventory, or import a CSV (Shopify too).',
    importCsv: 'Import',
    allTypes: 'All types',
  },
  editor: {
    add: 'Add product',
    titleLabel: 'Title',
    titlePlaceholder: 'e.g. Short sleeve t-shirt',
    description: 'Description',
    descriptionPlaceholder: 'Say what it is, who it is for and why it is worth it.',
    media: 'Media',
    drop: 'Drag images here',
    or: 'or',
    upload: 'Upload images',
    addUrl: 'Add from URL',
    urlPlaceholder: 'https://…/photo.jpg',
    addUrlButton: 'Add',
    formats: 'JPG, PNG, WebP or GIF · max 5 MB',
    main: 'Main',
    pending: 'Uploads on save',
    uploading: 'Uploading…',
    alt: 'Alt text',
    altHint: 'Describe the photo for screen readers and search engines.',
    removeImage: 'Remove image',
    moveLeft: 'Move earlier',
    moveRight: 'Move later',
    makeMain: 'Make main',
    tooBig: (name: string) => `${name} is larger than 5 MB.`,
    notImage: (name: string) => `${name} is not an image.`,
    pricing: 'Pricing',
    price: 'Price',
    compareAt: 'Compare-at price',
    compareAtHint: 'The old price, shown crossed out. Leave empty when there is no sale.',
    inventory: 'Inventory',
    track: 'Track quantity',
    trackHint: 'Counts down with each sale so you never sell what you do not have.',
    quantity: 'Quantity',
    sku: 'SKU (stock keeping unit)',
    continueSelling: 'Continue selling when out of stock',
    shipping: 'Shipping',
    physical: 'This is a physical product that ships',
    weight: 'Weight',
    variants: 'Variants',
    addOptions: 'Add options like size or color',
    optionName: 'Option name',
    optionNamePlaceholder: 'Size, Color, Material…',
    optionValues: 'Values',
    valuePlaceholder: 'Add a value and press Enter',
    addValue: 'Add value',
    addOption: 'Add another option',
    removeOption: 'Remove option',
    optionsDone: 'Done',
    editOptions: 'Edit options',
    variant: 'Variant',
    available: 'Available',
    maxOptions: 'Up to 3 options.',
    status: 'Status',
    statusHint: {
      active: 'Visible in your store.',
      draft: 'Hidden until you publish it.',
      archived: 'Hidden and out of the catalog.',
    },
    organization: 'Product organization',
    type: 'Type',
    typeLocked: 'The type cannot change after the product is created.',
    typeHints: {
      physical: 'Shipped or picked up.',
      digital: 'The customer downloads a file.',
      service: 'The customer books an appointment.',
    },
    collections: 'Collections',
    noCollections: 'You have no collections yet.',
    manageCollections: 'Manage collections',
    tags: 'Tags',
    tagsPlaceholder: 'Type and press Enter',
    removeTag: (tag: string) => `Remove ${tag}`,
    seo: 'Search engine listing',
    seoHint: 'How your product shows up on Google.',
    seoEdit: 'Edit',
    seoTitle: 'Page title',
    seoDescription: 'Meta description',
    chars: (n: number, max: number) => `${n} of ${max} characters used`,
    urlPreview: (slug: string) => `…/products/${slug || 'your-product'}`,
    digital: 'Digital file',
    digitalHint: 'Customers get a secure download link after paying.',
    digitalSaveFirst: 'Save the product to upload the file.',
    service: 'Service details',
    saved: 'Product saved',
    created: 'Product created',
    archived: 'Product archived',
    archiveConfirm: 'The product will be hidden from your store. Past orders are kept.',
    archiveTitle: (title: string) => `Archive ${title}?`,
    duplicate: 'Duplicate',
    viewInStore: 'View in store',
    back: 'Products',
    unsavedLeave: 'You have unsaved changes.',
    required: 'Enter a title.',
    priceRequired: 'Enter a price.',
  },
  inventoryPage: {
    title: 'Inventory',
    intro: 'How many units you have of each variant. Committed units are in checkouts being paid.',
    search: 'Search by product or SKU',
    tabs: { all: 'All', low: 'Low stock', out: 'Out of stock' },
    product: 'Product',
    sku: 'SKU',
    reserved: 'Committed',
    available: 'Available',
    onHand: 'On hand',
    adjust: 'Adjust',
    setTo: 'New total',
    save: 'Save',
    untracked: 'Not tracked',
    track: 'Track',
    reason: 'Manual adjustment in Inventory',
    updated: 'Inventory updated',
    empty: 'Nothing here.',
    emptyBody: 'Products with tracked inventory show up here.',
    threshold: (n: number) => `Showing variants with ${n} units or fewer.`,
    add: (n: number) => `+${n}`,
    remove: (n: number) => `−${n}`,
  },
  abandoned: {
    title: 'Abandoned checkouts',
    intro: 'Customers who reached checkout and did not pay. Email them their cart, ready to buy.',
    tabs: { all: 'All', abandoned: 'Not recovered', recovered: 'Recovered' },
    checkout: 'Checkout',
    date: 'Date',
    customer: 'Customer',
    items: 'Products',
    total: 'Total',
    recovery: 'Recovery',
    statuses: { abandoned: 'Not recovered', in_progress: 'Paying', recovered: 'Recovered' },
    sentAt: (when: string) => `Email sent · ${when}`,
    notSent: 'Email not sent',
    send: 'Send email',
    resend: 'Resend',
    copyLink: 'Copy cart link',
    copied: 'Link copied',
    sent: (email: string) => `Email sent to ${email}`,
    order: (n: number) => `Order #${n}`,
    more: (n: number) => `and ${n} more`,
    empty: 'No abandoned checkouts',
    emptyBody:
      'When someone enters their email at checkout and does not pay, you can recover it here.',
    autoOn: 'Recovery emails are sent automatically.',
    autoOff: 'Turn on automatic emails so you do not lose sales.',
    configure: 'Configure',
    noSite: 'Add your store URL to send recovery emails.',
    addSite: 'Add URL',
    loadMore: 'Load more',
  },
  orderView: {
    tabs: {
      all: 'All',
      unfulfilled: 'Unfulfilled',
      unpaid: 'Unpaid',
      open: 'Open',
      closed: 'Closed',
    },
    unfulfilled: 'Unfulfilled',
    fulfilled: 'Fulfilled',
    digital: 'Digital delivery',
    booking: 'Appointment',
    paid: 'Paid',
    pending: 'Payment pending',
    subtotalItems: (n: number) => (n === 1 ? '1 item' : `${n} items`),
    taxes: 'Taxes',
    total: 'Total',
    paidByCustomer: 'Paid by customer',
    refunded: 'Refunded',
    balance: 'Balance due',
    net: 'Net',
    printSlip: 'Print packing slip',
    more: 'More actions',
    notes: 'Notes',
    noNotes: 'No notes from customer.',
    contact: 'Contact information',
    viewCustomer: 'View customer',
    consents: 'Confirmations',
    comment: 'Leave a comment…',
    post: 'Post',
    commentPosted: 'Comment added',
    timeline: 'Timeline',
    noShippingAddress: 'No shipping address',
    channel: 'Channel',
    placed: (when: string) => `Placed on ${when}`,
    shippedWith: (carrier: string) => `Shipped with ${carrier}`,
    fulfilledToast: 'Order marked as shipped',
    refundedToast: 'Refund issued',
    cancelledToast: 'Order cancelled',
    resentToast: 'Confirmation resent',
    slip: {
      title: 'Packing slip',
      order: (n: number) => `Order #${n}`,
      shipTo: 'Ship to',
      billTo: 'Customer',
      items: 'Items',
      qty: 'Quantity',
      thanks: 'Thank you for your purchase!',
      print: 'Print',
    },
    noOrders: 'No orders match these filters.',
    paymentCol: 'Payment status',
    fulfillmentCol: 'Fulfillment status',
    moreFilters: 'More filters',
  },
  settingsNav: {
    title: 'Settings',
    sections: {
      general: 'General',
      payments: 'Payments',
      shipping: 'Shipping and delivery',
      taxes: 'Taxes',
      checkout: 'Checkout',
      notifications: 'Notifications',
      team: 'Team',
      agents: 'AI agents',
      webhooks: 'Webhooks',
      integrations: 'Integrations',
    },
    descriptions: {
      general: 'Store name, logo, color and contact',
      payments: 'Stripe, test mode and live payments',
      shipping: 'Rates, free shipping and pickup',
      taxes: 'Tax rate and how prices are shown',
      checkout: 'Store URL, confirmations and abandoned checkouts',
      notifications: 'Emails to your customers',
      team: 'Who can access the admin',
      agents: 'Your AI’s tokens and activity log',
      webhooks: 'Send events to other systems',
      integrations: 'Connections and APIs',
    },
  },
  general: {
    details: 'Store details',
    name: 'Store name',
    contact: 'Contact email',
    contactHint: 'Shown in customer emails so they can write to you.',
    brand: 'Brand',
    logo: 'Logo',
    logoHint: 'PNG, JPG, WebP or SVG, max 2 MB. Used in the admin and in emails.',
    uploadLogo: 'Upload logo',
    changeLogo: 'Change',
    removeLogo: 'Remove',
    color: 'Brand color',
    colorHint: 'Buttons in customer emails.',
    regional: 'Region',
    currency: 'Currency',
    country: 'Country',
    timezone: 'Time zone',
    regionalHint: 'The currency is set at install; prices and orders are stored in it.',
    saved: 'Settings saved',
    logoSaved: 'Logo updated',
  },
  shippingSettings: {
    rates: 'Shipping rates',
    ratesHint: 'What customers see at checkout.',
    flat: 'Standard shipping',
    freeOver: 'Free shipping from',
    freeOverHint: 'Leave empty if you do not offer free shipping.',
    pickup: 'Local pickup',
    pickupHint: 'Customers can choose to pick up for free.',
    preview: 'Checkout preview',
    free: 'Free',
    previewFree: (amount: string) => `Free on orders from ${amount}`,
  },
  taxSettings: {
    title: 'Taxes',
    rate: 'Tax rate',
    included: 'My prices already include taxes',
    includedHint: 'Common in Mexico and Europe: the price shown is what the customer pays.',
    shipping: 'Charge taxes on shipping',
    example: (price: string, tax: string) => `Example: on a ${price} product, the tax is ${tax}.`,
  },
  checkoutSettings: {
    site: 'Your online store',
    siteUrl: 'Store URL',
    siteUrlHint:
      'Where your store lives. Used in abandoned checkout emails and as the return page of payment links.',
    consent: 'Required checkbox',
    consentToggle: 'Ask for a confirmation before paying',
    consentHint: 'Useful for alcohol, minimum age or terms. Stored with each order as proof.',
    consentText: 'Checkbox text',
    consentPlaceholder: 'I confirm I am 18 or older',
    downloads: 'Downloads page',
    downloadsUrl: 'Downloads page URL (optional)',
    downloadsHint:
      'For digital products. Must contain {token}, e.g. https://yourstore.com/downloads/{token}.',
    abandoned: 'Abandoned checkouts',
    autoEmail: 'Send recovery emails automatically',
    autoEmailHint: 'Once per cart, with a link that opens the cart ready to pay.',
    delay: 'Send after',
    hours: (n: number) => (n === 1 ? '1 hour' : `${n} hours`),
    needsSite: 'Add your store URL to turn on recovery emails.',
  },
  notificationSettings: {
    provider: 'Email provider',
    connected: 'Resend connected',
    notConnected: 'Not connected',
    notConnectedHint:
      'Until you connect Resend, emails are only written to the server log and customers do not receive them.',
    apiKey: 'Resend API key (re_…)',
    apiKeyHint: 'Create it at resend.com/api-keys. Stored encrypted in Supabase Vault.',
    connect: 'Connect Resend',
    reconnect: 'Change API key',
    test: 'Send test email',
    testTo: 'Send to',
    testSent: 'Test email sent',
    testLogged: 'Resend is not connected: the test email was only written to the server log.',
    sender: 'Sender',
    senderHint: (from: string) => `Sent as “${from}”. Change it with SELLBASE_EMAIL_FROM.`,
    automatic: 'Automatic emails',
    automaticHint: 'Sent automatically with your logo and color.',
    templates: {
      order_confirmation: 'Order confirmation (with downloads and appointments)',
      order_shipped: 'Order shipped (with tracking)',
      order_refunded: 'Refund',
      order_cancelled: 'Order cancelled',
      booking_reminder: 'Appointment reminder (24 h and 2 h before)',
      booking_changed: 'Appointment rescheduled or cancelled',
      cart_recovery: 'Abandoned checkout (if enabled in Checkout)',
    },
  },
  integrationsPage: {
    intro:
      'Connect services with your API keys. They are stored encrypted in Supabase Vault, never in your code.',
    connected: 'Connected',
    notConnected: 'Not connected',
    error: 'Error',
    manage: 'Manage',
    connect: 'Connect',
    stripe: { name: 'Stripe', body: 'Card payments and more.' },
    resend: { name: 'Resend', body: 'Transactional email from your domain.' },
    agents: {
      name: 'Your AI (MCP)',
      body: 'Claude, Cursor or another agent runs the store with limited permissions.',
    },
    webhooks: { name: 'Webhooks', body: 'Send orders and events to your ERP, sheets or Zapier.' },
    api: {
      name: 'API and SDK',
      body: 'Your site uses the store’s public API (catalog, cart, checkout).',
    },
    apiUrl: 'API URL',
    docs: 'Documentation',
    active: (n: number) => `${n} active`,
  },
};
