const es = {
  nav: {
    home: 'Inicio',
    orders: 'Pedidos',
    products: 'Productos',
    settings: 'Ajustes',
    signOut: 'Salir',
  },
  login: {
    title: 'Entra a tu tienda',
    email: 'Correo',
    password: 'Contraseña',
    signIn: 'Entrar',
    magicLink: 'Enviarme un link de acceso',
    magicLinkSent: 'Revisa tu correo: te enviamos un link para entrar.',
    notStaff: 'Tu cuenta no es parte del equipo de esta tienda. Pide al dueño que te invite.',
  },
  home: {
    checks: {
      schema: 'Base de datos',
      rls: 'Seguridad (RLS)',
      store: 'Datos de la tienda',
      payments: 'Pagos',
      email: 'Correos de pedidos',
      catalog: 'Catálogo',
      webhooks: 'Webhooks de pago',
    } as Record<string, string>,
    title: 'Inicio',
    checklist: 'Lista de configuración',
    allGood: 'Todo listo para vender.',
    askAi: 'Pídeselo a tu IA',
    copy: 'Copiar',
    copied: 'Copiado',
  },
  orders: {
    title: 'Pedidos',
    empty: 'Aún no hay pedidos.',
    emptyPrompt:
      'Haz una compra de prueba en mi tienda con Sellbase y confírmame que llegó el pedido.',
    number: 'Pedido',
    customer: 'Cliente',
    total: 'Total',
    date: 'Fecha',
    status: 'Estado',
    all: 'Todos',
    items: 'Productos',
    payments: 'Pagos',
    timeline: 'Historial',
    shippingAddress: 'Dirección de envío',
    subtotal: 'Subtotal',
    discount: 'Descuento',
    shipping: 'Envío',
    back: '← Pedidos',
    actions: 'Acciones',
    fulfill: 'Marcar como enviado',
    carrier: 'Paquetería',
    trackingNumber: 'Número de guía',
    trackingUrl: 'URL de rastreo',
    notifyCustomer: 'Avisar al cliente por correo',
    refund: 'Reembolsar',
    refundAmount: 'Monto a reembolsar',
    reason: 'Motivo',
    cancelOrder: 'Cancelar pedido',
    restock: 'Regresar productos al inventario',
    refundToo: 'Reembolsar lo pagado',
    addNote: 'Agregar nota',
    resend: 'Reenviar confirmación',
    resent: 'Confirmación enviada',
    confirm: 'Confirmar',
    back2: 'Volver',
    refundImpact: (amount: string, email: string) =>
      `Se reembolsarán ${amount} a ${email} vía Stripe. No se puede deshacer.`,
    cancelImpact: (refund: string | null) =>
      `El pedido quedará cancelado y los links de descarga dejarán de funcionar.${refund ? ` Se reembolsarán ${refund}.` : ''}`,
    shipments: 'Envíos',
    refunds: 'Reembolsos',
    track: 'Rastrear',
    refundable: (amount: string) => `Reembolsable: ${amount}`,
    events: {
      'order.created': 'Pedido pagado.',
      'digital.granted': (n: number) => `Links de descarga enviados (${n}).`,
      test_purchase: 'Compra de prueba: el stock se regresó al inventario.',
      'fulfillment.created': (qty: number, carrier: string | null, tracking: string | null) =>
        `Enviado: ${qty} producto(s)${carrier ? ` con ${carrier}` : ''}${tracking ? ` (guía ${tracking})` : ''}.`,
      'refund.created': (amount: string, reason: string) => `Reembolso de ${amount}: ${reason}.`,
      'order.cancelled': (reason: string) => `Pedido cancelado: ${reason}.`,
      'notification.requested': 'Se pidió reenviar el correo.',
      'inventory.oversold': (n: number) => `Faltó stock al confirmar el pago: ${n} unidad(es).`,
      emailSent: (template: string) => `Correo enviado: ${template}.`,
      templates: {
        order_confirmation: 'confirmación',
        order_shipped: 'pedido en camino',
        order_refunded: 'reembolso',
        order_cancelled: 'cancelación',
      } as Record<string, string>,
    },
  },
  products: {
    title: 'Productos',
    new: 'Nuevo producto',
    empty: 'Aún no tienes productos.',
    emptyPrompt: 'Crea en Sellbase un producto activo con foto, precio y stock para mi tienda.',
    search: 'Buscar por nombre o SKU',
    name: 'Nombre',
    type: 'Tipo',
    status: 'Estado',
    price: 'Precio',
    stock: 'Stock',
    description: 'Descripción',
    variants: 'Variantes',
    addVariant: 'Agregar variante',
    variantTitle: 'Variante',
    sku: 'SKU',
    save: 'Guardar',
    saved: 'Guardado',
    archive: 'Archivar',
    images: 'Imágenes',
    addImage: 'Agregar imagen',
    file: 'Archivo para el comprador',
    uploadFile: 'Subir archivo',
    requiresShipping: 'Requiere envío',
    weight: 'Peso (g)',
    back: '← Productos',
    types: { physical: 'Físico', digital: 'Digital', service: 'Servicio' },
    statuses: { draft: 'Borrador', active: 'Activo', archived: 'Archivado' },
  },
  settings: {
    title: 'Ajustes',
    store: 'Tienda',
    storeName: 'Nombre de la tienda',
    contactEmail: 'Correo de contacto',
    brandColor: 'Color de marca',
    taxRate: 'IVA (%)',
    taxIncluded: 'Los precios incluyen impuestos',
    shipping: 'Envío',
    flatRate: 'Tarifa fija',
    freeOver: 'Envío gratis desde',
    pickup: 'Permitir recoger en tienda',
    payments: 'Pagos',
    stripeConnected: 'Stripe conectado',
    stripeNotConnected: 'Stripe no está conectado',
    secretKey: 'Llave secreta (sk_…)',
    webhookSecret: 'Secreto del webhook (whsec_…)',
    connect: 'Conectar',
    test: 'Probar conexión',
    save: 'Guardar',
    saved: 'Guardado',
  },
  status: {
    pending_payment: 'Pago pendiente',
    open: 'Abierto',
    completed: 'Completado',
    cancelled: 'Cancelado',
    unpaid: 'Sin pagar',
    partially_paid: 'Anticipo',
    paid: 'Pagado',
    partially_refunded: 'Reembolso parcial',
    refunded: 'Reembolsado',
    unfulfilled: 'Por surtir',
    partially_fulfilled: 'Surtido parcial',
    fulfilled: 'Surtido',
  },
  common: {
    loading: 'Cargando…',
    error: 'Algo salió mal.',
    retry: 'Reintentar',
    cancel: 'Cancelar',
    menu: 'Menú',
  },
};

export type Texts = typeof es;

const en: Texts = {
  nav: {
    home: 'Home',
    orders: 'Orders',
    products: 'Products',
    settings: 'Settings',
    signOut: 'Sign out',
  },
  login: {
    title: 'Sign in to your store',
    email: 'Email',
    password: 'Password',
    signIn: 'Sign in',
    magicLink: 'Email me a sign-in link',
    magicLinkSent: 'Check your inbox for a sign-in link.',
    notStaff: 'Your account is not on this store’s team. Ask the owner to invite you.',
  },
  home: {
    checks: {
      schema: 'Database',
      rls: 'Security (RLS)',
      store: 'Store details',
      payments: 'Payments',
      email: 'Order emails',
      catalog: 'Catalog',
      webhooks: 'Payment webhooks',
    } as Record<string, string>,
    title: 'Home',
    checklist: 'Setup checklist',
    allGood: 'Ready to sell.',
    askAi: 'Ask your AI',
    copy: 'Copy',
    copied: 'Copied',
  },
  orders: {
    title: 'Orders',
    empty: 'No orders yet.',
    emptyPrompt: 'Make a test purchase in my Sellbase store and confirm the order arrived.',
    number: 'Order',
    customer: 'Customer',
    total: 'Total',
    date: 'Date',
    status: 'Status',
    all: 'All',
    items: 'Items',
    payments: 'Payments',
    timeline: 'Timeline',
    shippingAddress: 'Shipping address',
    subtotal: 'Subtotal',
    discount: 'Discount',
    shipping: 'Shipping',
    back: '← Orders',
    actions: 'Actions',
    fulfill: 'Mark as shipped',
    carrier: 'Carrier',
    trackingNumber: 'Tracking number',
    trackingUrl: 'Tracking URL',
    notifyCustomer: 'Email the customer',
    refund: 'Refund',
    refundAmount: 'Amount to refund',
    reason: 'Reason',
    cancelOrder: 'Cancel order',
    restock: 'Return items to stock',
    refundToo: 'Refund what was paid',
    addNote: 'Add note',
    resend: 'Resend confirmation',
    resent: 'Confirmation sent',
    confirm: 'Confirm',
    back2: 'Back',
    refundImpact: (amount: string, email: string) =>
      `${amount} will be refunded to ${email} through Stripe. This cannot be undone.`,
    cancelImpact: (refund: string | null) =>
      `The order will be cancelled and download links will stop working.${refund ? ` ${refund} will be refunded.` : ''}`,
    shipments: 'Shipments',
    refunds: 'Refunds',
    track: 'Track',
    refundable: (amount: string) => `Refundable: ${amount}`,
    events: {
      'order.created': 'Order paid.',
      'digital.granted': (n: number) => `Download links sent (${n}).`,
      test_purchase: 'Test purchase: stock was returned.',
      'fulfillment.created': (qty: number, carrier: string | null, tracking: string | null) =>
        `Shipped ${qty} item(s)${carrier ? ` with ${carrier}` : ''}${tracking ? ` (tracking ${tracking})` : ''}.`,
      'refund.created': (amount: string, reason: string) => `Refunded ${amount}: ${reason}.`,
      'order.cancelled': (reason: string) => `Order cancelled: ${reason}.`,
      'notification.requested': 'Email resend requested.',
      'inventory.oversold': (n: number) => `Stock ran out before payment: ${n} unit(s).`,
      emailSent: (template: string) => `Email sent: ${template}.`,
      templates: {
        order_confirmation: 'confirmation',
        order_shipped: 'order shipped',
        order_refunded: 'refund',
        order_cancelled: 'cancellation',
      } as Record<string, string>,
    },
  },
  products: {
    title: 'Products',
    new: 'New product',
    empty: 'No products yet.',
    emptyPrompt: 'Create an active Sellbase product with a photo, price and stock for my store.',
    search: 'Search by name or SKU',
    name: 'Name',
    type: 'Type',
    status: 'Status',
    price: 'Price',
    stock: 'Stock',
    description: 'Description',
    variants: 'Variants',
    addVariant: 'Add variant',
    variantTitle: 'Variant',
    sku: 'SKU',
    save: 'Save',
    saved: 'Saved',
    archive: 'Archive',
    images: 'Images',
    addImage: 'Add image',
    file: 'File for the buyer',
    uploadFile: 'Upload file',
    requiresShipping: 'Requires shipping',
    weight: 'Weight (g)',
    back: '← Products',
    types: { physical: 'Physical', digital: 'Digital', service: 'Service' },
    statuses: { draft: 'Draft', active: 'Active', archived: 'Archived' },
  },
  settings: {
    title: 'Settings',
    store: 'Store',
    storeName: 'Store name',
    contactEmail: 'Contact email',
    brandColor: 'Brand color',
    taxRate: 'Tax (%)',
    taxIncluded: 'Prices include tax',
    shipping: 'Shipping',
    flatRate: 'Flat rate',
    freeOver: 'Free shipping over',
    pickup: 'Allow in-store pickup',
    payments: 'Payments',
    stripeConnected: 'Stripe connected',
    stripeNotConnected: 'Stripe is not connected',
    secretKey: 'Secret key (sk_…)',
    webhookSecret: 'Webhook secret (whsec_…)',
    connect: 'Connect',
    test: 'Test connection',
    save: 'Save',
    saved: 'Saved',
  },
  status: {
    pending_payment: 'Payment pending',
    open: 'Open',
    completed: 'Completed',
    cancelled: 'Cancelled',
    unpaid: 'Unpaid',
    partially_paid: 'Deposit',
    paid: 'Paid',
    partially_refunded: 'Partially refunded',
    refunded: 'Refunded',
    unfulfilled: 'To fulfill',
    partially_fulfilled: 'Partially fulfilled',
    fulfilled: 'Fulfilled',
  },
  common: {
    loading: 'Loading…',
    error: 'Something went wrong.',
    retry: 'Retry',
    cancel: 'Cancel',
    menu: 'Menu',
  },
};

export const texts = { es, en };
