// Bundles each Edge Function into supabase/functions/<name>/index.js (ADR 0005).
// The output is generated: never edit it by hand.
import { build } from 'esbuild';
import { mkdir, readFile } from 'node:fs/promises';
import { builtinModules } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const functionsDir = resolve(here, '../../supabase/functions');

const entries = {
  'sellbase-api': 'src/edge/api.ts',
  'sellbase-webhooks': 'src/edge/webhooks.ts',
  'sellbase-jobs': 'src/edge/jobs.ts',
};

const pkg = JSON.parse(await readFile(resolve(here, 'package.json'), 'utf8'));
const postgresVersion = pkg.dependencies.postgres.replace(/^[^\d]*/, '');

// postgres.js relies on Node globals (Buffer, setImmediate…). Loading it as an npm:
// specifier lets Deno apply its full Node compatibility layer instead of bundling it.
// Any other bare Node built-in gets the `node:` prefix Deno requires.
const denoImports = {
  name: 'deno-imports',
  setup(b) {
    const builtins = new Set(builtinModules);
    b.onResolve({ filter: /^postgres$/ }, () => ({
      path: `npm:postgres@${postgresVersion}`,
      external: true,
    }));
    b.onResolve({ filter: /^[a-z_]+(\/[a-z_]+)?$/ }, (args) =>
      builtins.has(args.path) ? { path: `node:${args.path}`, external: true } : undefined,
    );
  },
};

for (const [name, entry] of Object.entries(entries)) {
  const outfile = resolve(functionsDir, name, 'index.js');
  await mkdir(dirname(outfile), { recursive: true });
  await build({
    entryPoints: [resolve(here, entry)],
    outfile,
    bundle: true,
    format: 'esm',
    platform: 'neutral',
    target: 'es2022',
    mainFields: ['module', 'main'],
    conditions: ['deno', 'worker', 'browser', 'import', 'default'],
    external: ['node:*', 'npm:*'],
    plugins: [denoImports],
    banner: { js: '// Generated by @sellbase/api build. Do not edit.' },
    legalComments: 'none',
    logLevel: 'warning',
  });
  console.log(`built ${name}`);
}
