/*
 * Sellbase admin generated by `sellbase init` (Vite). Render it for every path under
 * /admin. It has its own router, so mount it once:
 *
 *   React Router:  <Route path="/admin/*" element={<SellbaseAdminPage />} />
 *   No router:     in src/main.tsx render <SellbaseAdminPage /> instead of <App /> when
 *                  window.location.pathname starts with "/admin".
 *
 * Your host must serve index.html for /admin/* (SPA fallback; Vite dev does it already).
 * Customize it through `config` (theme, texts, logo, slots, pages), never the package.
 */
import { SellbaseAdmin, type AdminConfig } from '@sellbase/admin';
import '@sellbase/admin/styles.css';

const config: AdminConfig = {
  supabaseUrl: import.meta.env.VITE_SUPABASE_URL ?? '',
  supabaseAnonKey: import.meta.env.VITE_SUPABASE_ANON_KEY ?? '',
  basePath: '/admin',
};

export default function SellbaseAdminPage() {
  return <SellbaseAdmin config={config} />;
}
