'use client';

/*
 * Sellbase admin generated by `sellbase init`. Customize it through `config` (theme,
 * texts, logo, slots, pages); never edit @sellbase/admin itself so updates keep working.
 */
import { SellbaseAdmin, type AdminConfig } from '@sellbase/admin';
import '@sellbase/admin/styles.css';

const config: AdminConfig = {
  supabaseUrl: process.env.NEXT_PUBLIC_SUPABASE_URL ?? '',
  supabaseAnonKey: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? '',
  basePath: '/admin',
};

export default function AdminPage() {
  return <SellbaseAdmin config={config} />;
}
