/*
 * Sellbase provider generated by `sellbase init` (Vite). Wrap your app with it once, e.g.
 * in src/main.tsx: <SellbaseStoreProvider><App /></SellbaseStoreProvider>
 */
import { SellbaseProvider } from '@sellbase/react';
import type { ReactNode } from 'react';

export function SellbaseStoreProvider({ children }: { children: ReactNode }) {
  return (
    <SellbaseProvider
      url={import.meta.env.VITE_SELLBASE_URL ?? ''}
      anonKey={import.meta.env.VITE_SUPABASE_ANON_KEY ?? ''}
    >
      {children}
    </SellbaseProvider>
  );
}
