// Builds the documentation agents read: docs/reference/api.md, docs/llms.txt,
// docs/llms-full.txt and the corpus bundled with the MCP server (docs_search,
// storefront_scaffold). `--check` fails if any output is stale (used in CI).
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');
const { routeList, BRAND } = await import(join(root, 'packages/core/dist/index.js'));

const read = (p) => readFile(join(root, p), 'utf8');

// ── API reference from the route contracts ──────────────────────────────────
const tags = [...new Set(routeList.map((r) => r.tag))];
let api = `# ${BRAND.name} API reference\n\nGenerated from the route contracts (\`packages/core/src/api/contracts.ts\`). Base URL: \`<SUPABASE_URL>/functions/v1/${BRAND.slug}-api/v1\`. Full schemas: \`GET /openapi.json\`.\n\nAuth: public routes need no token; the rest need \`Authorization: Bearer <staff session or ${BRAND.tokenPrefix}… token>\` with the scope shown. Money is an integer in minor units. Errors have \`code\`, \`message\` and \`hint\`.\n`;
for (const tag of tags) {
  api += `\n## ${tag}\n\n`;
  for (const r of routeList.filter((x) => x.tag === tag)) {
    const auth =
      r.auth.kind === 'public' ? 'public' : `scope: ${r.auth.scope ?? 'any staff or token'}`;
    api += `- **${r.method} ${r.path}** (${auth}): ${r.summary}.${r.description ? ` ${r.description}` : ''}\n`;
  }
}

// ── Sources for the corpus ───────────────────────────────────────────────────
const sources = [
  { path: 'README.md', title: 'README' },
  ...(await readdir(join(root, 'docs/guides')))
    .filter((f) => f.endsWith('.md'))
    .sort()
    .map((f) => ({ path: `docs/guides/${f}` })),
  ...(await readdir(join(root, 'skills'))).sort().map((d) => ({ path: `skills/${d}/SKILL.md` })),
  { path: 'docs/reference/api.md', content: api },
];

const strip = (md) => md.replace(/^---\n[\s\S]*?\n---\n/, '');
const sections = [];
let full = `# ${BRAND.name} — full documentation for AI agents\n`;
for (const src of sources) {
  const text = strip(src.content ?? (await read(src.path)));
  full += `\n\n<!-- source: ${src.path} -->\n\n${text.trim()}\n`;
  const title = src.title ?? /^# (.+)$/m.exec(text)?.[1] ?? src.path;
  // One searchable section per "## " heading (or the whole file).
  const parts = text.split(/^(?=## )/m);
  for (const part of parts) {
    const heading = /^## (.+)$/m.exec(part)?.[1];
    const body = part.trim();
    if (!body) continue;
    sections.push({
      source: src.path,
      title: heading ? `${title} › ${heading}` : title,
      text: body.slice(0, 6000),
    });
  }
}

const llms = `# ${BRAND.name}

> Open source, AI-first commerce kit that installs inside a project (its repo and its Supabase): catalog, checkout, orders, bookings, discounts, emails, an admin at /admin, an API and an MCP server.

Agents: connect the \`${BRAND.slug}\` MCP server (\`npx ${BRAND.cli} mcp\`), start with \`store_status\` and use \`docs_search\`. Money is always an integer in minor units.

## Docs

${sources.map((s) => `- [${s.title ?? s.path}](${s.path.replace(/^docs\//, '')}): ${s.path.startsWith('skills/') ? 'agent skill' : s.path.includes('reference') ? 'every API route' : 'guide'}`).join('\n')}

## Full text

- [llms-full.txt](llms-full.txt)
`;

const registry = JSON.parse(await read('packages/registry/registry.json')).components.map((c) => ({
  name: c.name,
  description: c.description,
  dependencies: c.registryDependencies,
}));
const corpus = `// Generated by scripts/build-docs.mjs. Do not edit; run \`pnpm docs:build\`.
export interface DocSection {
  source: string;
  title: string;
  text: string;
}

export const DOCS: DocSection[] = ${JSON.stringify(sections, null, 2)};

export const REGISTRY: { name: string; description: string; dependencies: string[] }[] = ${JSON.stringify(registry, null, 2)};
`;

const outputs = {
  'docs/reference/api.md': api,
  'docs/llms.txt': llms,
  'docs/llms-full.txt': full,
  'packages/mcp/src/docs.generated.ts': corpus,
};
const prettier = await import('prettier');
let stale = [];
for (const [path, raw] of Object.entries(outputs)) {
  const abs = join(root, path);
  const options = (await prettier.resolveConfig(abs)) ?? {};
  const content = path.endsWith('.txt')
    ? raw
    : await prettier.format(raw, { ...options, filepath: abs });
  const current = existsSync(abs) ? await readFile(abs, 'utf8') : null;
  if (current === content) continue;
  if (check) stale.push(path);
  else {
    await (await import('node:fs/promises')).mkdir(dirname(abs), { recursive: true });
    await writeFile(abs, content);
    console.log(`wrote ${relative(root, abs)}`);
  }
}
if (stale.length) {
  console.error(`Stale generated docs: ${stale.join(', ')}. Run \`pnpm docs:build\`.`);
  process.exit(1);
}
console.log(`${sections.length} doc sections, ${registry.length} components`);
